<?xml version="1.0" encoding="utf-8"?><Database Name="avalon_stats" Class="AvalonDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=avalon_stats;Persist Security Info=True;User ID=sa" SettingsObjectName="Avalon_Stats.Properties.Settings" SettingsPropertyName="avalon_statsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.gameRole" Member="GameRoles">
    <Type Name="GameRole">
      <Column Name="roleShortcut" Member="RoleShortcut" Storage="_roleShortcut" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="side" Member="Side" Storage="_side" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fullName" Member="FullName" Storage="_fullName" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Association Name="GameRole_Participation" Member="Participations" ThisKey="RoleShortcut" OtherKey="RoleShortcut" Type="Participation" />
    </Type>
  </Table>
  <Table Name="dbo.participation" Member="Participations">
    <Type Name="Participation">
      <Column Name="gameId" Member="GameId" Storage="_gameId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="playerName" Member="PlayerName" Storage="_playerName" Type="System.String" DbType="VarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="roleShortcut" Member="RoleShortcut" Storage="_roleShortcut" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Association Name="GameRole_Participation" Member="GameRole" ThisKey="RoleShortcut" OtherKey="RoleShortcut" Type="GameRole" IsForeignKey="true" />
      <Association Name="Game_Participation" Member="Game" Storage="_game" ThisKey="GameId" OtherKey="GameId" Type="Game" IsForeignKey="true" />
      <Association Name="GameView_Participation" Member="GameView" Storage="_gameView" ThisKey="GameId" OtherKey="GameId" Type="GameView" IsForeignKey="true" />
      <Association Name="Player_Participation" Member="Player" ThisKey="PlayerName" OtherKey="PlayerName" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.game" Member="Games">
    <Type Name="Game">
      <Column Name="gameId" Member="GameId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gameTime" Member="GameTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="firstMissionResult" Member="FirstMissionResult" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="secondMissionResult" Member="SecondMissionResult" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="thirdMissionResult" Member="ThirdMissionResult" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fourthMissionResult" Member="FourthMissionResult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="fithMissionResult" Member="FithMissionResult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="killedPlayer" Member="KilledPlayer" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Association Name="Game_Participation" Member="Participations" ThisKey="GameId" OtherKey="GameId" Type="Participation" />
      <Association Name="Player_Game" Member="Player" ThisKey="KilledPlayer" OtherKey="PlayerName" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.gameView" Member="GameViews">
    <Type Name="GameView">
      <Column Name="gameId" Member="GameId" Storage="_gameId" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gameTime" Member="GameTime" Storage="_gameTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="WonBy" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="GroupSize" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="firstMissionResult" Member="FirstMissionResult" Storage="_firstMissionResult" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="secondMissionResult" Member="SecondMissionResult" Storage="_secondMissionResult" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="thirdMissionResult" Member="ThirdMissionResult" Storage="_thirdMissionResult" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fourthMissionResult" Member="FourthMissionResult" Storage="_fourthMissionResult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="fithMissionResult" Member="FithMissionResult" Storage="_fithMissionResult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="killedPlayer" Member="KilledPlayer" Storage="_killedPlayer" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Association Name="GameView_Participation" Member="Participations" ThisKey="GameId" OtherKey="GameId" Type="Participation" />
      <Association Name="Player_GameView" Member="Player" ThisKey="KilledPlayer" OtherKey="PlayerName" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.player" Member="Players">
    <Type Name="Player">
      <Column Name="playerName" Member="PlayerName" Type="System.String" DbType="VarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="firstName" Member="FirstName" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Association Name="Player_Participation" Member="Participations" ThisKey="PlayerName" OtherKey="PlayerName" Type="Participation" />
      <Association Name="Player_Game" Member="Games" ThisKey="PlayerName" OtherKey="KilledPlayer" Type="Game" />
      <Association Name="Player_GameView" Member="GameViews" ThisKey="PlayerName" OtherKey="KilledPlayer" Type="GameView" />
    </Type>
  </Table>
</Database>